apiVersion: v1
kind: Service
metadata:
  name: mailfrom-milter
  labels:
    app: mailfrom-milter
spec:
  type: ClusterIP
  selector:
    app: mailfrom-milter
  ports:
    - name: milter
      port: {{ .Values.milterPort }}
      targetPort: milter
      protocol: TCP
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
